openapi: 3.0.3
info:
  title: API Fédération Collectivités Agricoles
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /collectivites:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Collectivite'
        required: true
      responses:
        "201":
          description: Collectivité créée avec succès
      summary: Ouverture d’une nouvelle collectivité
      x-content-type: application/json
      x-accepts:
      - application/json
  /membres:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Membre'
        required: true
      responses:
        "201":
          description: Membre admis avec succès
      summary: Admission d’un nouveau membre
      x-content-type: application/json
      x-accepts:
      - application/json
  /cotisations:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cotisation'
        required: true
      responses:
        "201":
          description: Cotisation enregistrée
      summary: Enregistrement d’une cotisation
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    Collectivite:
      example:
        ville: ville
        dateCreation: 2000-01-23
        specialite: specialite
        id: id
        nom: nom
        membres:
        - dateNaissance: 2000-01-23
          genre: masculin
          adresse: adresse
          telephone: telephone
          id: id
          poste: president
          nom: nom
          prenom: prenom
          email: email
          metier: metier
          dateAdhesion: 2000-01-23
        - dateNaissance: 2000-01-23
          genre: masculin
          adresse: adresse
          telephone: telephone
          id: id
          poste: president
          nom: nom
          prenom: prenom
          email: email
          metier: metier
          dateAdhesion: 2000-01-23
      properties:
        id:
          type: string
        nom:
          type: string
        ville:
          type: string
        specialite:
          type: string
        dateCreation:
          format: date
          type: string
        membres:
          items:
            $ref: '#/components/schemas/Membre'
          type: array
      type: object
    Membre:
      example:
        dateNaissance: 2000-01-23
        genre: masculin
        adresse: adresse
        telephone: telephone
        id: id
        poste: president
        nom: nom
        prenom: prenom
        email: email
        metier: metier
        dateAdhesion: 2000-01-23
      properties:
        id:
          type: string
        nom:
          type: string
        prenom:
          type: string
        dateNaissance:
          format: date
          type: string
        genre:
          enum:
          - masculin
          - feminin
          type: string
        adresse:
          type: string
        metier:
          type: string
        telephone:
          type: string
        email:
          type: string
        dateAdhesion:
          format: date
          type: string
        poste:
          enum:
          - president
          - presidentAdjoint
          - tresorier
          - secretaire
          - membreConfirme
          - membreJunior
          type: string
      type: object
    Cotisation:
      example:
        date: 2000-01-23
        modePaiement: espece
        montant: 0.8008281904610115
        id: id
        membreId: membreId
      properties:
        id:
          type: string
        membreId:
          type: string
        montant:
          type: number
        date:
          format: date
          type: string
        modePaiement:
          enum:
          - espece
          - virement
          - mobileMoney
          type: string
      type: object

